version: "3.8"

services:
  frontend:
    container_name: nextjs_frontend
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    # environment:
    #   - NODE_ENV=production

  backend:
    container_name: express_backend
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env  # Loads environment variables from backend/.env
